from .dataset_reader import UniversalDependenciesDatasetReader
from .model import JointTaggerParser
from .biaffine_parser import ArcBiaffine, LabelBilinear
from .basic_predictor import UniversalDependenciesBasicCharacterLevelPredictor
